// Mocks generated by Mockito 5.3.2 from annotations
// in hawker_hub/test/hub_search_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hawker_hub/models/hub.dart' as _i2;
import 'package:hawker_hub/services/hub_services.dart' as _i3;
import 'package:image_picker/image_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHub_0 extends _i1.SmartFake implements _i2.Hub {
  _FakeHub_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HubServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockHubServices extends _i1.Mock implements _i3.HubServices {
  MockHubServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Hub>> fetchAllHubs() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllHubs,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Hub>>.value(<_i2.Hub>[]),
      ) as _i4.Future<List<_i2.Hub>>);
  @override
  _i4.Future<_i2.Hub> insertHub(
    _i2.Hub? hubDetails,
    _i5.XFile? hubPhoto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertHub,
          [
            hubDetails,
            hubPhoto,
          ],
        ),
        returnValue: _i4.Future<_i2.Hub>.value(_FakeHub_0(
          this,
          Invocation.method(
            #insertHub,
            [
              hubDetails,
              hubPhoto,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Hub>);
  @override
  _i4.Future<_i2.Hub> updateHub(
    _i2.Hub? hubDetails,
    _i5.XFile? hubPhoto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHub,
          [
            hubDetails,
            hubPhoto,
          ],
        ),
        returnValue: _i4.Future<_i2.Hub>.value(_FakeHub_0(
          this,
          Invocation.method(
            #updateHub,
            [
              hubDetails,
              hubPhoto,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Hub>);
}
